rule_files:
  - alert.yml

scrape_configs:
  - job_name: node_exporter
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - '10.0.0.56:9100'

  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.86:9187']